services:
  ch3rn1k-web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ch3rn1k.rule=Host(`ch3rn1k.me`)'
      - 'traefik.http.routers.ch3rn1k.entrypoints=websecure'
      - 'traefik.http.routers.ch3rn1k.tls.certresolver=letsencrypt'
      - 'traefik.http.services.ch3rn1k.loadbalancer.server.port=80'
    networks:
      - web

networks:
  web:
    external: true
